# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    serializer:
        serialize_null: true
